<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ProductsTableSeeder extends Seeder
{
    public function run()
    {
        // Chaussures
        DB::table('products')->insert([
            [
                'name' => 'chaussure medicale',
                'description' => 'Chaussure orthopédique conçue pour offrir un soutien maximal et soulager les douleurs chroniques du pied, idéale pour les personnes ayant des problèmes de posture ou de mobilité.',
                'price' => 99.99,
                'image' => 'storage/products/chaussures/chaussure_medicale.jpg',
                'color' => 'Blanc',
                'taille' => '42',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'chaussure decharge avant-pied_1',
                'description' => 'Chaussure de décharge spécialement conçue pour alléger la pression sur l\'avant-pied, parfaite pour les personnes souffrant d\'ulcères ou de blessures à l\'avant du pied.',
                'price' => 129.99,
                'image' => 'storage/products/chaussures/chaussure-decharge-avant-pied_1.jpg',
                'color' => 'Noir',
                'taille' => '40',
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Cheville
        DB::table('products')->insert([
            [
                'name' => 'aircast airselect elite',
                'description' => 'Chevillière haut de gamme avec système de compression ajustable pour une stabilité optimale après une blessure ou une opération.',
                'price' => 85.99,
                'image' => 'storage/products/cheville/aircast_airselect_elite.jpg',
                'color' => 'Bleu',
                'taille' => 'M',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'airselect courte',
                'description' => 'Modèle court de la chevillière Airselect, idéale pour les blessures légères et la prévention des entorses.',
                'price' => 70.00,
                'image' => 'storage/products/cheville/airselect-courte.jpg',
                'color' => 'Gris',
                'taille' => 'S',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'airselect standard',
                'description' => 'Chevillière standard avec système de maintien ajustable pour un soutien de la cheville adapté à vos besoins.',
                'price' => 72.00,
                'image' => 'storage/products/cheville/airselect-standard.jpg',
                'color' => 'Noir',
                'taille' => 'M',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'chevillere avec renforts lateraux',
                'description' => 'Chevillière renforcée pour un soutien latéral supplémentaire, idéale pour les personnes souffrant de douleurs chroniques à la cheville.',
                'price' => 95.00,
                'image' => 'storage/products/cheville/chevillere_avec_renforts_lateraux.jpg',
                'color' => 'Noir',
                'taille' => 'L',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'chevillere de compression sport',
                'description' => 'Chevillière de compression conçue pour les athlètes, afin de réduire l’inflammation et améliorer la circulation sanguine.',
                'price' => 65.00,
                'image' => 'storage/products/cheville/chevillere_de_compression_sport.jpg',
                'color' => 'Bleu',
                'taille' => 'M',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'malleotrain-s',
                'description' => 'Orthèse pour la cheville permettant un mouvement naturel tout en offrant un soutien efficace et une compression ciblée.',
                'price' => 105.00,
                'image' => 'storage/products/cheville/malleotrain-s.jpg',
                'color' => 'Noir',
                'taille' => 'M',
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Cou
        DB::table('products')->insert([
            [
                'name' => 'collier cervical pediatrique',
                'description' => 'Collier cervical pédiatrique, conçu pour offrir un soutien doux mais efficace pour les jeunes enfants souffrant de douleurs au cou.',
                'price' => 40.00,
                'image' => 'storage/products/cou/collier_cervical_pediatrique.jpg',
                'color' => 'Blanc',
                'taille' => 'S',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'collier cervical avec ouverture tracheale',
                'description' => 'Collier cervical avec ouverture trachéale pour permettre une respiration facile tout en offrant un soutien optimal au cou.',
                'price' => 55.00,
                'image' => 'storage/products/cou/collier-cervical-avec-ouverture-tracheale.jpg',
                'color' => 'Gris',
                'taille' => 'L',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'collier cervical vario thuasne',
                'description' => 'Collier cervical ajustable Thuasne, idéal pour un soutien personnalisé et une réduction des douleurs cervicales.',
                'price' => 65.00,
                'image' => 'storage/products/cou/collier-cervical-vario-thuasne.jpg',
                'color' => 'Gris',
                'taille' => 'M',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'collier cervical',
                'description' => 'Collier cervical standard pour soulager les douleurs du cou et offrir un soutien thérapeutique.',
                'price' => 35.00,
                'image' => 'storage/products/cou/collier_cervical.jpg',
                'color' => 'Blanc',
                'taille' => 'L',
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // Coude
        DB::table('products')->insert([
            [
                'name' => 'Bandage Coude Aircast',
                'description' => 'Bandage de coude Aircast, conçu pour fournir un soutien et un soulagement rapide des douleurs au coude.',
                'price' => 33.00,
                'image' => 'storage/products/coude/bandage-coude-aircast.jpg',
                'color' => 'Noir',
                'taille' => 'M',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Coudière avec Renforts Latéraux',
                'description' => 'Coudière avec renforts latéraux pour plus de stabilité et de soutien après une blessure ou une opération.',
                'price' => 149.99,
                'image' => 'storage/products/coude/coudiere_avec_renforts_lateraux.jpg',
                'color' =>  'Bleu',
                'taille' => 'L',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Coudière Élastique Soutien',
                'description' => 'Coudière élastique offrant un soutien léger mais efficace pour les douleurs chroniques du coude.',
                'price' => 89.99,
                'image' => 'storage/products/coude/coudiere_elastique_soutien.jpg',
                'color' =>  'Noir',
                'taille' => 'M',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Donjoy Écharpe',
                'description' => 'Écharpe de soutien Donjoy, idéale pour maintenir le bras et le coude dans une position confortable après une blessure.',
                'price' => 99.99,
                'image' => 'storage/products/coude/donjoy-echarpe.jpg',
                'color' =>  'Bleu',
                'taille' => 'M',
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // Cuisse et hanche
        
        DB::table('products')->insert([
            [
                'name' => 'CSM Myotrain',
                'description' => 'Orthèse de cuisse Myotrain pour soutenir les muscles et articulations de la cuisse tout en permettant une récupération rapide.',
                'price' =>66.00,
                'image' => 'storage/products/cuisse et hanche/csm_myotrain.jpg',
                'color' =>  'Bleu',
                'taille' => 'L',
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ezyplast Accessoire',
                'description' => 'Accessoire Ezyplast pour un soutien additionnel lors de blessures de la cuisse et des hanches.',
                'price' => 144.00,
                'image' => 'storage/products/cuisse et hanche/ezyplast_accessoire.png',
                'color' => 'Rouge',
                'taille' => 'L',
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jupystrap Pubalgie Grossesse',
                'description' => 'Soutien pour la pubalgie et la grossesse, idéal pour soulager les douleurs liées aux hanches et au bassin.',
                'price' => 230.00,
                'image' => 'storage/products/cuisse et hanche/jupystrap-pubalgie-grossesse.jpg',
                'color' => 'Rose',
                'taille' => 'M',
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Shortystrap Long',
                'description' => 'Shorty de compression pour un soutien maximal des hanches et de la cuisse, idéal pour la rééducation après une blessure.',
                'price' => 120.00,
                'image' => 'storage/products/cuisse et hanche/shortystrap-long.jpg',
                'color' => 'Noir',
                'taille' => 'L',
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // Dos
        DB::table('products')->insert([
            [
                'name' => 'Ceinture Dorsale Sport Médicale',
                'description' => 'Ceinture dorsale sportive médicale, conçue pour offrir un soutien renforcé au bas du dos lors d’activités physiques.',
                'price' => 120.00,
                'image' => 'storage/products/dos/ceinture_dorsale_sport_medical.jpg',
                'color' => 'bleu',
                'taille' => 'L',
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ceinture Souple Confort',
                'description' => 'Ceinture souple et confortable pour un soutien léger du bas du dos, idéale pour soulager les douleurs lombaires.',
                'price' => 170.00,
                'image' => 'storage/products/dos/ceinture_souple_confort.jpg',
                'color' => 'bleu',
                'taille' => 'M',
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ceinture Lumbotrain',
                'description' => 'Ceinture Lumbotrain pour stabiliser la région lombaire et offrir un confort tout au long de la journée.',
                'price' => 50.00,
                'image' => 'storage/products/dos/ceinture-lumbotrain.png',
                'color' => 'noir',
                'taille' => 'M',
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ceinture Maternité Enceinte',
                'description' => 'Ceinture de maternité pour soutenir le ventre et le bas du dos pendant la grossesse, réduisant ainsi les douleurs lombaires.',
                'price' => 150.00,
                'image' => 'storage/products/dos/ceinture-maternite-enceinte.jpg',
                'color' => 'rose',
                'taille' => 'S',
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Orthèse Dorsale Orthodos',
                'description' => 'Orthèse dorsale Orthodos pour améliorer la posture et soulager les douleurs au niveau du dos.',
                'price' => 150.00,
                'image' => 'storage/products/dos/orthodos.png',
                'color' => 'noir',
                'taille' => 'M',
                'category_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // Epaule
        DB::table('products')->insert([
            [
                'name' => 'Contention pour l\'épaule Donjoy',
                'description' => 'Contention pour l’épaule Donjoy, idéale pour maintenir l’articulation stable après une blessure ou une opération.',
                'price' => 45.00,
                'image' => 'storage/products/epaule/donjoy-contention.jpg',
                'color' => 'blanc',
                'taille' => 'M',
                'category_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Écharpe de Contention Donjoy',
                'description' => 'Écharpe de contention Donjoy pour soutenir l’épaule et le bras, idéale après une chirurgie.',
                'price' => 45.00,
                'image' => 'storage/products/epaule/donjoy-echarpe-contention.png',
                'color' => 'blanc',
                'taille' => 'L',
                'category_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Orthèse Omotrain',
                'description' => 'Orthèse Omotrain pour la rééducation de l’épaule, offrant un soutien et une compression contrôlée.',
                'price' => 50.00,
                'image' => 'storage/products/epaule/omotrain.jpg',
                'color' => 'blanc',
                'taille' => 'S',
                'category_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // Insert products for Genou category
        DB::table('products')->insert([
            [
                'name' => 'Attelle de Genou Genuimmo',
                'description' => 'Attelle de genou Genuimmo pour la rééducation après une chirurgie du genou, offrant une stabilité et un soutien maximal.',
                'price' => 78.00,
                'image' => 'storage/products/genou/attelle-de-genou-genuimmo.jpg',
                'color' => 'beige',
                'taille' => 'L',
                'category_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Genouillère FullForce Donjoy',
                'description' => 'Genouillère FullForce Donjoy pour un soutien optimal et une protection contre les blessures graves du genou.',
                'price' => 55.00,
                'image' => 'storage/products/genou/fullforce-donjoy.jpg',
                'color' => 'beige',
                'taille' => 'M',
                'category_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Genouillère de Maintien Sport',
                'description' => 'Genouillère de maintien sportif pour les athlètes, offrant une stabilité et une protection accrues lors des activités physiques.',
                'price' => 55.00,
                'image' => 'storage/products/genou/genouillère-de-maintien-sport.jpg',
                'color' => 'beige',
                'taille' => 'L',
                'category_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Genouillère Ligamentaire',
                'description' => 'Genouillère ligamentaire pour soutenir les ligaments du genou et réduire le risque de blessures.',
                'price' => 455.00,
                'image' => 'storage/products/genou/genouillère-ligamentaire.jpg',
                'color' =>'gris',
                'taille' => 'M',
                'category_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        // Insert products for Pied category
        DB::table('products')->insert([
            [
                'name' => 'Achillotrain Pro',
                'description' => 'Orthèse Achillotrain Pro pour le traitement des douleurs au tendon d’Achille.',
                'price' =>  76.00,
                'image' => 'storage/products/pied/achillotrain-pro.jpg',
                'color' => 'noir',
                'taille' => 'L',
                'category_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Airselect Courte',
                'description' => 'Airselect Courte pour une protection optimale du pied tout en favorisant la guérison.',
                'price' => 100,
                'image' => 'storage/products/pied/airselect-courte.jpg',
                'color' => 'noir',
                'taille' => 'M',
                'category_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Semelle Viscoped',
                'description' => 'Semelle Viscoped pour un soutien optimal et une réduction des douleurs sous le pied.',
                'price' =>236.00,
                'image' => 'storage/products/pied/semelle_viscoped_detail.jpg',
                'color' => 'beige',
                'taille' => 'L',
                'category_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Viscoheelk',
                'description' => 'Viscoheelk pour soulager la douleur au talon et au pied, favorisant la guérison des blessures.',
                'price' => 78.00,
                'image' => 'storage/products/pied/viscoheelk.jpg',
                'color' => 'beige',
                'taille' => 'L',
                'category_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
            // Insert products for Poignet, Main et Doigt category
        DB::table('products')->insert([
            [
                'name' => 'Attelle de Stack en Mousse et Aluminium',
                'description' => 'Attelle de Stack en mousse et aluminium pour maintenir et soutenir l’articulation du poignet.',
                'price' => 33.00,
                'image' => 'storage/products/poignet-main-doigt/attelle-de-stack-en-mousse-et-aluminium.jpg',
                'color' => 'violet',
                'taille' => 'M',
                'category_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Attelle Rhizoloc',
                'description' => 'Attelle Rhizoloc pour offrir un soutien efficace aux douleurs de l’articulation du poignet.',
                'price' => 78.00,
                'image' => 'storage/products/poignet-main-doigt/attelle-rhizoloc.jpg',
                'color' => 'blanc',
                'taille' => 'L',
                'category_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Attelle Spica',
                'description' => 'Attelle Spica pour stabiliser et soutenir les articulations du poignet et du pouce.',
                'price' => 250.00,
                'image' => 'storage/products/poignet-main-doigt/attelle-spica.jpg',
                'color' =>  'blanc',
                'taille' => 'M',
                'category_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Attelle Type Zimmer',
                'description' => 'Attelle type Zimmer pour maintenir l’articulation du poignet dans une position fonctionnelle.',
                'price' => 250.00,
                'image' => 'storage/products/poignet-main-doigt/attelle-type-zimmer.jpg',
                'color' =>  'blanc',
                'taille' => 'S',
                'category_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
           
        ]);
        // Insert products for Ventre category
        DB::table('products')->insert([
            [
                'name' => 'Bande Ceinture Thoracique Cemen Thuasne',
                'description' => 'Bande ceinture thoracique Cemen Thuasne pour offrir un soutien optimal à la région thoracique.',
                'price' =>275.00,
                'image' => 'storage/products/ventre/bande-ceinture-thoracique-cemen-thuasne.jpg',
                'color' => 'beige',
                'taille' => 'L',
                'category_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ceinture de Ventre',
                'description' => 'Ceinture de ventre pour offrir un soutien léger et confortable pendant la grossesse ou après.',
                'price' => 200.00,
                'image' => 'storage/products/ventre/ceinture-de-ventre.jpg',
                'color' => 'blanc',
                'taille' => 'M',
                'category_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Donjoy Ceinture Femme Abdostrap',
                'description' => 'Ceinture Abdostrap pour femme Donjoy, conçue pour soutenir la région abdominale.',
                'price' => 58.00,
                'image' => 'storage/products/ventre/donjoy-ceinture-femme-abdostrap.jpg',
                'color' => 'rose',
                'taille' => 'S',
                'category_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ]);    
    }
}